version: '3'
services:
    #   App Docker
    metabeemRelayMedia:                       # Service Name
        container_name: metabeem-relay-media
        hostname: metabeem-relay-media
        build:
            context: .
        image: metabeem-relay-media:latest
        ports:
            # 指定端口映射，类似 docker run 的 -p 选项，注意使用字符串形式
            # [local port]:[container port]
            - "6612:6612"
        volumes:
            - ./deploy/etc/denetwork/.swarmKey:/etc/denetwork/.swarmKey:ro
            - ./deploy/etc/hosts:/etc/hosts:ro
            #- ./deploy/etc/localtime:/etc/localtime:ro
            #- ./deploy/etc/timezone:/etc/timezone:ro

#        environment:
#            - REDIS_HOST=redis
#            - REDIS_PORT=6379
#            - NODE_ENV=production
#        depends_on:
#            redis:
#                condition: service_healthy
#        links:
#            - redis
#
#    #   Redis Docker
#    redis:
#        image: redis:latest
#        healthcheck:
#            test: ["CMD", "redis-cli", "ping"]
#            interval: 1s
#            timeout: 2s
#            retries: 10
